<template>
    <div class="w-full">
        <h3 class="myTitle">Home</h3>
        <div class="flex flex-row gap-10 p-4">
            <div class="homeCard">
                <div class="homeCardHeader">
                    <p class="homeCardHeaderText">SLA/OLA Management</p>
                </div>
                <p class="homeCardContent">A way of visualising the SLA/OLA Management and edit where necessary </p>
                <div class="homeCardBtnContainer">
                    <button class="outlineBtn">Visual Open</button>
                    <button class="filledBtn">Edit Open</button>
                </div>
            </div>

            <div class="homeCard">
                <div class="homeCardHeader">
                    <p class="homeCardHeaderText">Fault Prioritization and Escalation</p>
                </div>
                <p class="homeCardContent">A way of visualising the SLA/OLA Management and edit where necessary </p>
                <div class="homeCardBtnContainer">
                    <button class="outlineBtn">Visual Open</button>
                    <button class="filledBtn">Edit Open</button>
                </div>
            </div>

            <div class="homeCard">
                <div class="homeCardHeader">
                    <p class="homeCardHeaderText">Overall Fault Management System</p>
                </div>
                <p class="homeCardContent">A way of visualising the SLA/OLA Management and edit where necessary </p>
                <div class="homeCardBtnContainer">
                    <button class="outlineBtn">Visual Open</button>
                    <button class="filledBtn">Edit Open</button>
                </div>
            </div>

            <div class="homeCard">
                <div class="homeCardHeader">
                    <p class="homeCardHeaderText">Report Generation</p>
                </div>
                <p class="homeCardContent">A way of visualising the SLA/OLA Management and edit where necessary </p>
                <div class="homeCardBtnContainer">
                    <button class="outlineBtn">Visual Open</button>
                    <button class="filledBtn">Edit Open</button>
                </div>
            </div>
        </div>

        <div class="flex flex-col gap-10 p-4">
            <div class="homeCardFull">
                <div class="homeCardHeader">
                    <p class="homeCardHeaderText">Database View</p>
                </div>
                <p class="homeCardContent">A way of visualising the SLA/OLA Management and edit where necessary </p>
                <div class="homeCardBtnContainerFull">
                    <button class="outlineBtn">Visual Open</button>
                    <button class="filledBtn">Edit Open</button>
                </div>
            </div>

            <div class="homeCardFull">
                <div class="homeCardHeader">
                    <p class="homeCardHeaderText">Dashboard and Analysis</p>
                </div>
                <p class="homeCardContent">Digital dashboard containing information and summary reports of the data generated by the AI model and the fixes it contains</p>
                <div class="homeCardBtnContainerFull">
                    <button class="outlineBtn">Visual Open</button>
                    <button class="filledBtn">Edit Open</button>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>

</script>

<style scoped>

    .myTitle {
            @apply text-[#007AFF] text-lg font-medium p-4 uppercase
        }

    .homeCard {
        @apply w-72 border border-[#007AFF] bg-slate-100 text-[#007AFF] rounded-lg pb-2
    }

    .homeCardFull {
        @apply w-full border border-[#007AFF] bg-slate-100 text-[#007AFF] rounded-lg pb-2
    }

    .homeCardHeader {
        @apply w-full border-b border-[#007AFF]
    }

    .homeCardHeaderText {
        @apply p-4 text-sm font-medium
    }

    .homeCardContent {
        @apply text-xs p-4
    }

    .homeCardBtnContainer {
        @apply flex flex-row p-4 justify-between
    }

    .homeCardBtnContainerFull {
        @apply flex flex-row p-4 gap-6 justify-end
    }

    .outlineBtn {
        @apply px-5 py-2 border border-[#007AFF] text-xs rounded-full hover:shadow duration-200
    }

    .filledBtn {
        @apply px-5 py-2 bg-[#007AFF] text-xs text-white rounded-full hover:shadow duration-200
    }
</style>